### ISSUE TITLE
Bug after open the custom drawer	

### ISSUE THREAD

**Issue by wassim6** [mitesh77/Best-Flutter-UI-Templates#12]
**Describe the bug**
After open the custom drawer and return to the Home screen, all bouton will open the custom drawer. it work fine on the emulator.

**To Reproduce**
1. Open the custom drawer
2. Close the drawer
3. Click on Design Course
4. See error, the custom drawer will be opened.

**Expected behavior**
Go to the Design Course Screen.

**Smartphone (please complete the following information):**
 - Device: Xiaomi redmi note 7
 - OS: Android 9

**Comment by therichiekumar** [comment]
I'm also face this issue in Xiaomi K20 Pro

**Comment by edTheGuy00** [comment]
@wassim6 So you take this entire project, sell it as a template on codecanyon.net then you have the balls to open up an issue about the issues your customers are facing? Seriously dude?

**Comment by JoeyHengst** [comment]
@wassim6  seriously dude?

**Comment by edTheGuy00** [comment]
@JoeyHengst He already got banned from codecanyon.net Good lol

https://codecanyon.net/user/wassim6/portfolio

https://codecanyon.net/item/top-flutter-ui-templates

**Comment by mitesh77** [comment]
please try again and check (this is a stable channel), (you can also re-clone project please and try)

**Comment by VyankeshH** [comment]
@mitesh77 Did you get any solution on this ?? I have same issue in My Xiaomi redmi note 7.

**Comment by mitesh77** [comment]
@VyankeshH , I will solve as soon as

**Comment by therichiekumar** [comment]
Thanks @mitesh77

**Comment by M9Apar** [comment]
it is happening with all Mi Device running OS Android 9 and Up, tested with POCO F1, Redmi note 7 Pro

**Comment by harrypatel07** [comment]
Hello guys,

Any update on this issue?

**Comment by FreezeSoul** [comment]
I fixed the issues after added the following code
**widget.drawerWidth - scrollController.offset > 0.1**
```
else if (scrollController.offset > 0 &&
            scrollController.offset < widget.drawerWidth &&
            widget.drawerWidth - scrollController.offset > 0.1) {
          iconAnimationController.animateTo(
              (scrollController.offset * 100 / (widget.drawerWidth)) / 100,
              duration: const Duration(milliseconds: 0),
              curve: Curves.linear);
 }
```
