### ISSUE TITLE
Rename the file to follow the Dart guidelines

### ISSUE THREAD

**Issue by jeancsanchez** [mitesh77/Best-Flutter-UI-Templates#15]
I think you could rename the project's file to follow the [guidelines](https://dart.dev/guides/language/effective-dart/style) with lowercase and undescore. Just an improvment :)

`
Some file systems are not case-sensitive, so many projects require filenames to be all lowercase. Using a separating character allows names to still be readable in that form. Using underscores as the separator ensures that the name is still a valid Dart identifier, which may be helpful if the language later supports symbolic imports.
`

**Comment by mitesh77** [comment]
I updated for this issue thanks for loothood
