### ISSUE TITLE
debug 报错

### ISSUE THREAD

**Issue by ranshon** [mitesh77/Best-Flutter-UI-Templates#19]
Exception has occurred.
FlutterError (ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized.
If you're running an application and need to access the binary messenger before `runApp()` has been called (for example, during plugin initialization), then you need to explicitly call the `WidgetsFlutterBinding.ensureInitialized()` first.
If you're running a test, you can call the `TestWidgetsFlutterBinding.ensureInitialized()` as the first line in your test's `main()` method to initialize the binding.)

**Comment by JustinTsouDeveloper** [comment]
same issue.

**Comment by JustinTsouDeveloper** [comment]
I have same issue, but my flutter channel change from dev to stable. It's work! You can try it.

**Comment by bolaji007** [comment]
Please I'm new to programming and I have issues when I run my code..please see error message below what went wrong:execution failed for task':app:compiledebugrenderscript'.>11vm-rs-cc is missing
![IMG-20191112-WA0016](https://user-images.githubusercontent.com/57984702/69224591-22bf4780-0b7d-11ea-84e3-e9d42b11f75a.jpeg)

**Comment by JustinTsouDeveloper** [comment]
You enter "flutter doctor -v" command have any error?

**Comment by bolaji007** [comment]
No error from flutter doctor
    On Friday, November 22, 2019, 03:15:27 AM GMT+1, JustinTsou <notifications@github.com> wrote:  
 
 
You enter "flutter doctor -v" command have any error?

**Comment by mitesh77** [comment]
I solve this issue anyone can check, please.
