### ISSUE TITLE
Where did you get the illustrations?

### ISSUE THREAD

**Issue by allenind** [mitesh77/Best-Flutter-UI-Templates#22]
Hello @mitesh77, I was just wondering where did you get your illustrations and such as I have based my final school project on your fitness app template, and I believe that I have to reference all the images and illustrations in my paper. Thanks in advance!

**Comment by mitesh77** [comment]
I fined on the dribble follow the links: https://dribbble.com/shots/6678348-My-Diary-Page-for-Fitness-App-Interaction
