### ISSUE TITLE
How to use this template?

### ISSUE THREAD

**Issue by IHNEL** [mitesh77/Best-Flutter-UI-Templates#25]
Hi, 
thank you for your sharing.
I'm newbie and I would like to know how can I apply/install this template in my project. Could you tell me some points?

**Comment by Ashbuhrz** [comment]
metoo.....can anyone help

**Comment by SeifKaroui** [comment]
I don't now how to use it as template but you can import the project and view the code by downloading the "best_flutter_ui_templates" folder and opening it with android studio. Some erros will show up so head over to  "Run" on the top bar then "Edit Configuration" after that click the add button and choose "Flutter" and put the directory of the flutter SDK(where you downloaded it) then hit apply.
If the run button doesn't work then go to File>Settings>Languages and frameworks>Enable Dart support for flutter projects then apply . Everything should be ok now.

**Comment by hackxxj** [comment]
Hi,
thank you for your sharing.
I'm newbie and I would like to know how can I apply/install this template in my project. Could you tell me some points?

**Comment by hackxxj** [comment]
What should I do if I want to transplant the second theme?

**Comment by SeifKaroui** [comment]
> What should I do if I want to transplant the second theme?

To be honest i don't really know how to do it. I just tried to read the code so i can understand how it's made  in order to use some of it my coming projects and implement it in my way.

**Comment by hackxxj** [comment]
> > What should I do if I want to transplant the second theme?
> 
> To be honest i don't really know how to do it. I just tried to read the code so i can understand how it's made in order to use some of it my coming projects and implement it in my way.

Thank you for your answer, because I'm a novice, I really don't know how to start.

**Comment by hackxxj** [comment]
If you have time, can I help you?

**Comment by SeifKaroui** [comment]
> If you have time, can I help you?

Sure !! If i can, i will be glad to help you.

**Comment by hackxxj** [comment]
> 。

Can I add your contact information

**Comment by hackxxj** [comment]
> > 如果有时间，我可以帮您吗？
> 
> 当然可以！如果可以的话，我很乐意为您提供帮助。

Can I add your contact information

**Comment by SeifKaroui** [comment]
> > > 如果有时间，我可以帮您吗？
> > 
> > 
> > 当然可以！如果可以的话，我很乐意为您提供帮助。
> 
> Can I add your contact information

Eris Sword#9136 that's my discord

**Comment by Balakanna** [comment]
Hi Mitesh,
Will you help me to work on my flutter project?

**Comment by protectedfor** [comment]
@mitesh77 could you please provide versions of your environment? What gradle version is used in this template?

I'm stuck with issue and I can't successfully run build command.

When I press build the following errors appear in Run window:

```
aunching lib/main.dart on Android SDK built for x86 in debug mode...
[!] Your app isn't using AndroidX.
    To avoid potential build failures, you can quickly migrate your app by following the steps on https://goo.gl/CP92wY.
Running Gradle task 'assembleDebug'...
.....
.....
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugKotlin'.
> Compilation error. See log for more details
```

Then I've tried to run `gradle` command (for example: `gradle clean build`) from console to see more detailed output but still there are errors:

```
$ gradle clean build
Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details

> Task :app:compileDebugKotlin FAILED
w: Runtime JAR files in the classpath should have the same version. These files were found in the classpath:
    /home/protectedfor/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk7/1.2.71/4ce93f539e2133f172f1167291a911f83400a5d0/kotlin-stdlib-jdk7-1.2.71.jar (version 1.2)
    /home/protectedfor/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.3.31/11289d20fd95ae219333f3456072be9f081c30cc/kotlin-stdlib-1.3.31.jar (version 1.3)
    /home/protectedfor/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.3.31/20c34a04ea25cb1ef0139598bd67c764562cb170/kotlin-stdlib-common-1.3.31.jar (version 1.3)
w: Some runtime JAR files in the classpath have an incompatible version. Consider removing them from the classpath
e: /home/protectedfor/AndroidStudioProjects/eggfood/android/app/src/main/kotlin/com/eggfood/eggfood/MainActivity.kt: (3, 28): Unresolved reference: NonNull
e: /home/protectedfor/AndroidStudioProjects/eggfood/android/app/src/main/kotlin/com/eggfood/eggfood/MainActivity.kt: (9, 42): Unresolved reference: NonNull
e: /home/protectedfor/AndroidStudioProjects/eggfood/android/app/src/main/kotlin/com/eggfood/eggfood/MainActivity.kt: (10, 48): Type mismatch: inferred type is FlutterEngine but PluginRegistry! was expected

FAILURE: Build failed with an exception.

```

$ gradle -v:

```
------------------------------------------------------------
Gradle 6.1
------------------------------------------------------------

Build time:   2020-01-15 23:56:46 UTC
Revision:     59d277fdba571ebc9617a3432983d7d2b259e3a4

Kotlin:       1.3.61
Groovy:       2.5.8
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          1.8.0_201 (Oracle Corporation 25.201-b09)
OS:           Linux 4.15.0-74-generic amd64

```

**Comment by mitesh77** [comment]
i will set

**Comment by mitesh77** [comment]
I fix AndroidX. you can check on commit

**Comment by alex-battikha** [comment]
Hi Mitesh,

Can you please assist me in getting this code to work in visual studio code. When I try to run, I have problems with the void paint statement on line 115 in range_slider_view.dart as well slider_view.dart. Any help is greatly appreciated!

**Comment by mitesh77** [comment]
use flutter stable channel with vscode.

**Comment by mitesh77** [comment]
@alex-battikha please check new flutter 1.17.0 stable, not mater channel.
