### ISSUE TITLE
Bugs in landscape mode

### ISSUE THREAD

**Issue by giaur500** [mitesh77/Best-Flutter-UI-Templates#28]
I unlocked landscape mode and it works incorrectly in landscape mode:
- drawer opens itself on orientation change to landscape
- unable to click anything on screen - on any click, drawer opens itself

How to use it with landscape mode?

**Comment by cv692001** [comment]
Hey @giaur500 , I am interested in doing this can you please elaborate :)

**Comment by cv692001** [comment]
Hey @giaur500  , can you please help 👍

**Comment by giaur500** [comment]
How can I help? You can try, enable rotation in this sample, rotate phone and see what happens. Drawer will open itself after screen rotates

**Comment by mitesh77** [comment]
this dome UI is for only portrait mode.

**Comment by baimamboukar** [comment]
if landscape mode is not really needed....  You can define the DeviceOrientations that you wants as so:
Inside your **build method, and just before the return** `SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp]);`
By doing so, your device will behave as same as in  landscape mode  as in protrait

**Comment by giaur500** [comment]
Actually, landscape mode is always needed. Why not?
