### ISSUE TITLE
Blank screen if any other idget is used as the root in the build method

### ISSUE THREAD

**Issue by DennisMuchiri** [mitesh77/Best-Flutter-UI-Templates#30]
When a column is used in place of a Listview in a listview, the UI does not render.

**Comment by DennisMuchiri** [comment]
this occurs at the getMainListViewUI() function

**Comment by mitesh77** [comment]
It is simple if we used list view then we set inside expand or some proper height or width we need to set. if you need to add a column then column child does not have an expanded widget. I guess you can understand.
