### ISSUE TITLE
Menu drawer not closing 

### ISSUE THREAD

**Issue by ksankumar** [mitesh77/Best-Flutter-UI-Templates#33]
1. Open the menu drawer.
2. Tab the native back button.(Android)
3. Drawer not getting closed.

**Comment by mitesh77** [comment]
it working fine. no issue

**Comment by ksankumar** [comment]
is this closing if you tab back button in android?

**Comment by emem365** [comment]
@mitesh77 , He is trying to close the drawer by pressing the native back button  on his screen. While the drawer, mostly does this on its own, since you've created a custom drawer, you might have overlooked this. I can look into this if you'd like :)

**Comment by emem365** [comment]
We probably just need to wrap the whole thing in a WillPopScope widget. I can create a PR, if you'd like to add this
