### ISSUE TITLE
how to add new pages?

### ISSUE THREAD

**Issue by uzairpawaskar** [mitesh77/Best-Flutter-UI-Templates#34]
Adding new pages, i am unable to navigate after design course, when we click on design course details show up.. what if different pages are there for different course.. how should we add them? and how to navigate through it?

**Comment by uzairpawaskar** [comment]
as i read the code and have seen when we click on any design course it calls moveto() function in home_design_course and goes to another screen which is course_info_screen 

my question is, how to navigate that when clicking on a particular item of list it should open particular page, 
for ex: if clicked on web design course.. it should open details about web design course,
i tried doing it from switch case but couldn't do it.. newbie in this can anyone help please

**Comment by mitesh77** [comment]
you can add new data on lib/model/homeList inside array you can check it
