### ISSUE TITLE
Drawer opens when it should not

### ISSUE THREAD

**Issue by giaur500** [mitesh77/Best-Flutter-UI-Templates#37]
Test on Android.
To reproduce:
- open drawer
- don't choose any menu option, swipe on blank space inside drawer menu to close drawer
- tap inside window where drawer is located. Unable to click anything, drawer opens itself

On some phones it's even worse, drawer always opens itself and I am unable to click anything in window. It depends from font size and dpi used. 
Drawer is buggy, please look?

**Comment by emem365** [comment]
Hi @mitesh77, I really appreciate what you've done with flutter here. I was looking around your examples when I faced the same issue. I managed to fix it for my fork of the repo. If this repo is open to PRs, maybe you can merge it to the master :)

**Comment by giaur500** [comment]
I can confirm, fix works fine.
