### ISSUE TITLE
Can't run app

### ISSUE THREAD

**Issue by IOCloudFly** [mitesh77/Best-Flutter-UI-Templates#38]
<img width="1291" alt="QQ20200507-185345@2x" src="https://user-images.githubusercontent.com/45480314/81286747-25aee580-9094-11ea-9671-6c8a3fc5f129.png">

download Flutter project,A lot of error.I don't know what.

**Comment by trbarton** [comment]
@IOCloudFly I had exactly the same. Upgraded flutter to v1.17 to match latest code changes and works fine now.

**Comment by rajivyadav23** [comment]
Upgraded to flutter to v1.17 but still error.

**Comment by TinNova** [comment]
@trbarton that worked, here is a link on how to upgrade your flutter:
https://flutter.dev/docs/development/tools/sdk/upgrading

However, it would be good to let people know in the readme.

**Comment by fareezMaple** [comment]
try click pub get in widget_test.dart, or to any file that showing the errors

**Comment by JAATBHAIJI** [comment]
1.)navigate to dart sdk
2.) Get dependencies

**Comment by zyllus17** [comment]
If it still shows error on ```color``` or ```vsync``` property, update environment sdk from 2.7.0 to 2.8.0
``````environment:
  sdk: ">=2.8.0 <3.0.0"
``````

**Comment by buildJava** [comment]
> If it still shows error on `color` or `vsync` property, update environment sdk from 2.7.0 to 2.8.0
> 
> ```
>   sdk: ">=2.8.0 <3.0.0"
> ```

restart ide will solve the problem，project could not rebuild
