### ISSUE TITLE
Does not support newer flutter version - throws  paint function parameter issue.

### ISSUE THREAD

**Issue by ArunEdathadan** [mitesh77/Best-Flutter-UI-Templates#42]
the errors say the arguments are not valid,   but the solution runs fine in older flutter SDKs

**Comment by VengasAlejandro** [comment]
Im having the same issues, any info you guys  might need to resolve this. I would gladly help :)

**Comment by VengasAlejandro** [comment]
@ArunEdathadan   use the changes on the next pull request to solve the problem. Or wait so it gets merged
#41

**Comment by chamin96** [comment]
@VengasAlejandro Your suggestion is correct. Runs fine with flutter version 1.20.0.
Thank you :)

**Comment by davidtomlin841** [comment]
Green tumb  how do you paint a thumb green

**Comment by mitesh77** [comment]
IT is already fixed.
