### ISSUE TITLE
different course info pages

### ISSUE THREAD

**Issue by dhhash** [mitesh77/Best-Flutter-UI-Templates#43]
hy this is a awesome work man. this is based on the design course template. Is there any way that i can open different course info pages for  different list item. as of now every list items open the same course info page. please help me how to open different pages for different list.

**Comment by davidtomlin841** [comment]
Hulk  skin color a pound of make up

**Comment by cv692001** [comment]
Hey @dhhash  , can you please elaborate the issue more
