### ISSUE TITLE
Bottom navigation vanishes. 

### ISSUE THREAD

**Issue by ghoshnilotpal8** [mitesh77/Best-Flutter-UI-Templates#44]
Hey, I added an extra screen to the fitness App, I added it at the bottom navigation at extreme right where the profile icon is, when I tap on the button the page translates to a different page but the bottom navigation vanishes. Any help would be appreciated, and there is no error displaying too.

**Comment by qqjay2017** [comment]
find file `/best_flutter_ui_templates/lib/fitness_app/fitness_app_home_screen.dart `
find Widget `bottomBar` 
edit `changeIndex`  method

```
...
else if(index == 3){
...
 tabBody =
                      YourScreenClass(animationController: animationController);
...
}
...
```

**Comment by pulsepas** [comment]
Anyone could help with Using this navigation bar?

I can switch screens by tapping navigation buttons, but how address changeIndex method from screen controls itself?
For example how to make screen transition to TrainingScreen when taping Meal Card in the MyDiarySceen?

**Comment by fg2q1q3q** [comment]
> Thank you @mitesh77 for a great App template!
> 
> Anyone could help with Using this navigation bar?
> 
> I can switch screens by tapping navigation buttons, but how address changeIndex method from the screen controls itself?
> For example how to make a screen transition to TrainingScreen when taping Meal Card in the MyDiarySceen? @qqjay2017
> ![Скриншот 19-03-2021 152956](https://user-images.githubusercontent.com/15133739/111735695-2e816200-88c8-11eb-84a0-7be052bcdd76.jpg)

I think you need code like this

------------fitness_app_home_screen.dart-------------
```
void goNavidationIndex(int index){
     tabIconsList.forEach((TabIconData tab) {
         tab.isSelected = false;
         tabIconsList[index].isSelected = true;
         changeIndex(index);//Need to extract the changeIndex method 
     }
}
```
Then you need to pass the method as a parameter to the click event of the child page

**Comment by pulsepas** [comment]
Thanks @fg2q1q3q !

Could you provide more information on how to pass the method as a parameter to the widget?
I have lost in documentation, nothing works for me.

**Comment by fg2q1q3q** [comment]
> Thanks @fg2q1q3q !
> 
> Could you provide more information on how to pass the method as a parameter to the widget?
> I have lost in documentation, nothing works for me.

[The code is here](https://gitee.com/yue7/FUI_Navigation)

![demo gif](https://gitee.com/yue7/FUI_Navigation/raw/master/tgirf-y0v9h.gif)

**Comment by pulsepas** [comment]
> > Thanks @fg2q1q3q !
> > Could you provide more information on how to pass the method as a parameter to the widget?
> > I have lost in documentation, nothing works for me.
> 
> [The code is here](https://gitee.com/yue7/FUI_Navigation)

Hey!
You saved my flutter project! I really appreciate your help! 
I want to buy you a coffee :)

**Comment by fg2q1q3q** [comment]
@pulsepas 
I'm glad to be able to help you. It's not worth mentioning
