### ISSUE TITLE
Web - there are any visual defects - CRASH

### ISSUE THREAD

**Issue by maurobotta** [mitesh77/Best-Flutter-UI-Templates#45]
Hi 

i have tested project on Web, don't work well.   

Compile but there are more visual fail.

Flutter (Channel beta, 1.19.0-4.1.pre, on Microsoft Windows [Versione 10.0.18363.959], locale it-IT)

//import 'dart:io';
import 'package:universal_io/io.dart';

**Comment by maurobotta** [comment]
I have compiled again with last version,

change src:
//import 'dart:io';
import 'package:universal_io/io.dart';

compiled for Web, run.... open site well , click on My Diary image ( CRASH )

[√] Flutter (Channel beta, 1.21.0-9.1.pre, on Microsoft Windows [Versione 10.0.18363.1016], locale it-IT)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.0)
[√] Connected device (3 available)


MY-DIARY CRASH

ERROR LOGS:



When the exception was thrown, this was the stack
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 212:49  throw_
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 24:3    assertFailed
packages/flutter/src/widgets/shortcuts.dart 329:33                                                                         handleKeypress
packages/flutter/src/widgets/shortcuts.dart 472:20                                                                         [_handleOnKey]
packages/flutter/src/widgets/focus_manager.dart 1625:43                                                                    [_handleRawKeyEvent]



════════ Exception caught by scheduler library ═════════════════════════════════
UnimplementedError
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by scheduler library ═════════════════════════════════
PersistedOffset: is in an unexpected state.
Expected one of: PersistedSurfaceState.active, PersistedSurfaceState.released
But was: PersistedSurfaceState.pendingRetention
════════════════════════════════════════════════════════════════════════════════

**Comment by aniketambore** [comment]
You can fix the above error by just replacing the **main.dart** with the below code :- 
```
import 'package:ui_template/app_theme.dart';
import 'package:flutter/material.dart';
import 'navigation_home_screen.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter UI',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.blue,
        textTheme: AppTheme.textTheme,
        platform: TargetPlatform.iOS,
      ),
      home: NavigationHomeScreen(),
    );
  }
}

class HexColor extends Color {
  HexColor(final String hexColor) : super(_getColorFromHex(hexColor));

  static int _getColorFromHex(String hexColor) {
    hexColor = hexColor.toUpperCase().replaceAll('#', '');
    if (hexColor.length == 6) {
      hexColor = 'FF' + hexColor;
    }
    return int.parse(hexColor, radix: 16);
  }
}
```
---
Run:- **_flutter run -d web-server --web-port 7357_**
---
Open:- localhost:7357
---
![Screenshot (462)](https://user-images.githubusercontent.com/52826253/107038540-aeed7700-67e2-11eb-955e-c7ddec1fb30c.png)

**Comment by mitesh77** [comment]
this project is not designed for the Web but I will do something next month. so maybe work
