### ISSUE TITLE
`FontAwesomeIcons` and  `DateFormat`  Classes are undefined in hotel booking

### ISSUE THREAD

**Issue by asmoun41** [mitesh77/Best-Flutter-UI-Templates#48]
Classes `FontAwesomeIcons` and `DateFormat` are undefined , inside the 'hotel booking' folder in those files :

- calendar_popup_view.dart
- custom_calendar.dart
- hotel_list_view.dart
- hotel_home_screen.dart

**Comment by cv692001** [comment]
Hey @asmoun41  , I will like to contribute to this can you please help 👍

**Comment by asmoun41** [comment]
@cv692001  yeh sure with pleasure.
