### ISSUE TITLE
'get dependencies and upgrade dependencies' buttons doesn't work..

### ISSUE THREAD

**Issue by NamVictoria** [mitesh77/Best-Flutter-UI-Templates#52]
![image](https://user-images.githubusercontent.com/69965746/93660780-587ad880-fa8d-11ea-8d1f-35d85dcef8ea.png)

How to solve this problem ?

My flutter version is 1.2.
![image](https://user-images.githubusercontent.com/69965746/93660793-806a3c00-fa8d-11ea-91f8-007b7b79948e.png)

sdk path
![image](https://user-images.githubusercontent.com/69965746/93660802-9972ed00-fa8d-11ea-8346-dddb8aae6d40.png)
![image](https://user-images.githubusercontent.com/69965746/93660811-a42d8200-fa8d-11ea-862c-004721037366.png)

please help me ㅠㅠ

**Comment by NamVictoria** [comment]
It's done !!
**I just deleted previous file and  installed again zip file!!.**
now it works well

**Comment by mitesh77** [comment]
ok fine
