### ISSUE TITLE
SystemChrome.setPreferredOrientations(           [DeviceOrientation.portraitUp, DeviceOrientation.portraitDown])       .then((_) => runApp(new MyApp())); is not working properly

### ISSUE THREAD

**Issue by Parmendrakumar** [mitesh77/Best-Flutter-UI-Templates#7]
Getting white screen on Mobile with 
SystemChrome.setPreferredOrientations(
          [DeviceOrientation.portraitUp, DeviceOrientation.portraitDown])
      .then((_) => runApp(new MyApp()));

Its working fine with
   runApp(new MyApp());

So, What is the use of 
SystemChrome.setPreferredOrientations(
          [DeviceOrientation.portraitUp, DeviceOrientation.portraitDown])
      .then((_) => runApp(new MyApp()));

**Comment by mitesh77** [comment]
it's run all app in portrait mode, its nothing but the custom drawer is not working properly in landscape mode. so I use this method.

what mobile model, please give me the name of mobile?

**Comment by csbzy** [comment]
I test both Pixel XL and iPhone8 plus. 
Only Getting white screen

**Comment by mitesh77** [comment]
I run again no issue found, please re-clon and check its. bro.

**Comment by Parmendrakumar** [comment]
I have tested it on Master branch and its working fine
