### ISSUE TITLE
Any plans to support web?

### ISSUE THREAD

**Issue by nicolairobles** [mitesh77/Best-Flutter-UI-Templates#70]
Currently I get the below error when trying to implement on web:

```The following UnsupportedError was thrown building MyApp(dirty):
js_primitives.dart:30 Unsupported operation: Platform._operatingSystem
```

**Comment by zp19931128** [comment]
me  too

**Comment by kevin4dhd** [comment]
Me too

**Comment by zp19931128** [comment]
I solved it. Can I tell you how to solve it

**Comment by zp19931128** [comment]
![image](https://user-images.githubusercontent.com/20333195/115536679-a5958600-a2cc-11eb-9a0c-e18c86053e2a.png)
