### ISSUE TITLE
Cant run project

### ISSUE THREAD

**Issue by salehasadi** [mitesh77/Best-Flutter-UI-Templates#80]
Hi @mitesh77 I cloned project but when I trigger flutter run it throws lots of errors in console.

> FAILURE: Build failed with an exception.                                
                                                                        
* Where:                                                                
Build file '/home/thunder/Projects/flutter_projects/Best-Flutter-UI-Templates/best_flutter_ui_templates/android/app/build.gradle' line: 26
                                                                        
* What went wrong:                                                      
A problem occurred evaluating project ':app'.                           
> Could not resolve all artifacts for configuration 'classpath'.        
   > Could not find aapt2-proto.jar (com.android.tools.build:aapt2-proto:4.1.0-6503028).
     Searched in the following locations:                               
         https://dl.google.com/dl/android/maven2/com/android/tools/build/aapt2-proto/4.1.0-6503028/aapt2-proto-4.1.0-6503028.jar
   > Could not find crash.jar (com.android.tools.analytics-library:crash:27.1.0).
     Searched in the following locations:                               
         https://dl.google.com/dl/android/maven2/com/android/tools/analytics-library/crash/27.1.0/crash-27.1.0.jar
   > Could not find gradle-api.jar (com.android.tools.build:gradle-api:4.1.0).
     Searched in the following locations:                               
         https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle-api/4.1.0/gradle-api-4.1.0.jar
   > Could not find databinding-compiler-common.jar (androidx.databinding:databinding-compiler-common:4.1.0).
     Searched in the following locations:                               
         https://dl.google.com/dl/android/maven2/androidx/databinding/databinding-compiler-common/4.1.0/databinding-compiler-common-4.1.0.jar
   > Could not find builder-model.jar (com.android.tools.build:builder-model:4.1.0).
     Searched in the following locations:                               
         https://dl.google.com/dl/android/maven2/com/android/tools/build/builder-model/4.1.0/builder-model-4.1.0.jar
   > Could not find builder-test-api.jar (com.android.tools.build:builder-test-api:4.1.0).
     Searched in the following locations:                               
         https://dl.google.com/dl/android/maven2/com/android/tools/build/builder-test-api/4.1.0/builder-test-api-4.1.0.jar
   > Could not find ddmlib.jar (com.android.tools.ddms:ddmlib:27.1.0).  
     Searched in the following locations:                               
         https://dl.google.com/dl/android/maven2/com/android/tools/ddms/ddmlib/27.1.0/ddmlib-27.1.0.jar
   > Could not find signflinger.jar (com.android:signflinger:4.1.0).    
     Searched in the following locations:                               
         https://dl.google.com/dl/android/maven2/com/android/signflinger/4.1.0/signflinger-4.1.0.jar
   > Could not find zipflinger.jar (com.android:zipflinger:4.1.0).      
     Searched in the following locations:                               
         https://dl.google.com/dl/android/maven2/com/android/zipflinger/4.1.0/zipflinger-4.1.0.jar
   > Could not find tracker.jar (com.android.tools.analytics-library:tracker:27.1.0).
     Searched in the following locations:                               
         https://dl.google.com/dl/android/maven2/com/android/tools/analytics-library/tracker/27.1.0/tracker-27.1.0.jar
   > Could not find sdklib.jar (com.android.tools:sdklib:27.1.0).       
     Searched in the following locations:                               
         https://dl.google.com/dl/android/maven2/com/android/tools/sdklib/27.1.0/sdklib-27.1.0.jar
   > Could not find layoutlib-api.jar (com.android.tools.layoutlib:layoutlib-api:27.1.0).
     Searched in the following locations:                               
         https://dl.google.com/dl/android/maven2/com/android/tools/layoutlib/layoutlib-api/27.1.0/layoutlib-api-27.1.0.jar
   > Could not find dvlib.jar (com.android.tools:dvlib:27.1.0).         
     Searched in the following locations:                               
         https://dl.google.com/dl/android/maven2/com/android/tools/dvlib/27.1.0/dvlib-27.1.0.jar
   > Could not find repository.jar (com.android.tools:repository:27.1.0).
     Searched in the following locations:                               
         https://dl.google.com/dl/android/maven2/com/android/tools/repository/27.1.0/repository-27.1.0.jar
   > Could not find shared.jar (com.android.tools.analytics-library:shared:27.1.0).
     Searched in the following locations:                               
         https://dl.google.com/dl/android/maven2/com/android/tools/analytics-library/shared/27.1.0/shared-27.1.0.jar
   > Could not find common.jar (com.android.tools:common:27.1.0).       
     Searched in the following locations:                               
         https://dl.google.com/dl/android/maven2/com/android/tools/common/27.1.0/common-27.1.0.jar
   > Could not find jetifier-processor.jar (com.android.tools.build.jetifier:jetifier-processor:1.0.0-beta09).
     Searched in the following locations:                               
         https://dl.google.com/dl/android/maven2/com/android/tools/build/jetifier/jetifier-processor/1.0.0-beta09/jetifier-processor-1.0.0-beta09.jar
   > Could not find jetifier-core.jar (com.android.tools.build.jetifier:jetifier-core:1.0.0-beta09).
     Searched in the following locations:                               
         https://dl.google.com/dl/android/maven2/com/android/tools/build/jetifier/jetifier-core/1.0.0-beta09/jetifier-core-1.0.0-beta09.jar
   > Could not find protos.jar (com.android.tools.analytics-library:protos:27.1.0).
     Searched in the following locations:                               
         https://dl.google.com/dl/android/maven2/com/android/tools/analytics-library/protos/27.1.0/protos-27.1.0.jar
   > Could not find core-proto.jar (com.google.test.platform:core-proto:0.0.2-dev).
     Searched in the following locations:                               
         https://dl.google.com/dl/android/maven2/com/google/test/platform/core-proto/0.0.2-dev/core-proto-0.0.2-dev.jar
   > Could not find apkzlib.jar (com.android.tools.build:apkzlib:4.1.0).
     Searched in the following locations:                               
         https://dl.google.com/dl/android/maven2/com/android/tools/build/apkzlib/4.1.0/apkzlib-4.1.0.jar
   > Could not find apksig.jar (com.android.tools.build:apksig:4.1.0).  
     Searched in the following locations:                               
         https://dl.google.com/dl/android/maven2/com/android/tools/build/apksig/4.1.0/apksig-4.1.0.jar
   > Could not find annotations.jar (com.android.tools:annotations:27.1.0).
     Searched in the following locations:                               
         https://dl.google.com/dl/android/maven2/com/android/tools/annotations/27.1.0/annotations-27.1.0.jar
   > Could not find databinding-common.jar (androidx.databinding:databinding-common:4.1.0).
     Searched in the following locations:                               
         https://dl.google.com/dl/android/maven2/androidx/databinding/databinding-common/4.1.0/databinding-common-4.1.0.jar
   > Could not find baseLibrary.jar (com.android.databinding:baseLibrary:4.1.0).
     Searched in the following locations:                               
         https://dl.google.com/dl/android/maven2/com/android/databinding/baseLibrary/4.1.0/baseLibrary-4.1.0.jar
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 1m 18s                                                  
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                        79.2s
Exception: Gradle task assembleDebug failed with exit code 1

could you please help me about that?

**Comment by SungmanHong** [comment]
me too!!

**Comment by eslamelhadedy** [comment]
me too!!

**Comment by mitesh77** [comment]
flutter v3 update, all issue fixed
