### ISSUE TITLE
This app is using a deprecated version of the Android embedding

### ISSUE THREAD

**Issue by YUHAI0** [mitesh77/Best-Flutter-UI-Templates#89]
When I run this template it comes:
This app is using a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to migrate this app to the V2 embedding.
Could owner do some migrations to this project?

**Comment by mitesh77** [comment]
donw now

**Comment by mitesh77** [comment]
new flutter v3 setup done in the project
