### ISSUE TITLE
Screenshots design

### ISSUE THREAD

**Issue by bipitup** [mitesh77/Best-Flutter-UI-Templates#9]
Hey buddy, I've no question about code.

I'm new in mobile designing. 

I want to know that how i make awesome screenshots like yours.

**Comment by mitesh77** [comment]
please, try yourself: every situation(code, error,) make a better understanding of flutter.

**Comment by bipitup** [comment]
@mitesh77 No, I want to be a product designer. I want to know which software you use to create screenshot.

**Comment by mitesh77** [comment]
I am not a UI designer fine on dribbble, please. I used thses image from dribbble, you can check its.
